global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["fastapi:8001"]
    metrics_path: "/metrics"

rule_files:
  - "alert.rules.yml"
