{
 "title": "FastAPI - Dashboard copy",
 "time": { "from": "2023-06-05T18:00:01.429Z", "to": "2023-06-05T18:10:01.429Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_usage\n" }
   ]
  },
  {
   "title": "API Status",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "memory_usage" }
   ]
  },
  {
   "title": "Failures detected",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(error_total{}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Endpoints traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(endpoint_calls_total{}[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}