{
 "title": "FastAPI - Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_usage\n" }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "memory_usage" }
   ]
  },
  {
   "title": "Failures detected",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(error_total{}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Endpoints traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(endpoint_calls_total{}[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}